/***********************************I-DEP-MAM-MAT-0-06/01/2017****************************************/
ALTER TABLE mat.tsolicitud
 ADD CONSTRAINT testado_wf_fk FOREIGN KEY (id_estado_wf)
    REFERENCES wf.testado_wf(id_estado_wf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE,

ALTER TABLE mat.tsolicitud
 ADD CONSTRAINT tfuncionario_fk FOREIGN KEY (id_funcionario_sol)
    REFERENCES orga.tfuncionario(id_funcionario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE,

ALTER TABLE mat.tsolicitud
  ADD CONSTRAINT tmatricula_fk FOREIGN KEY (id_matricula)
    REFERENCES conta.torden_trabajo(id_orden_trabajo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE,

ALTER TABLE mat.tsolicitud
  ADD CONSTRAINT tproceso_wf_fk FOREIGN KEY (id_proceso_wf)
    REFERENCES wf.tproceso_wf(id_proceso_wf)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE,

ALTER TABLE mat.tsolicitud
  ADD CONSTRAINT tproveedor_fk FOREIGN KEY (id_proveedor)
    REFERENCES param.tproveedor(id_proveedor)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE

/***********************************F-DEP-MAM-MAT-0-06/01/2017****************************************/

/***********************************I-DEP-MAM-MAT-1-06/01/2017****************************************/
ALTER TABLE mat.tdetalle_sol
ADD CONSTRAINT tsolicitud_sol_fk FOREIGN KEY (id_solicitud)
    REFERENCES mat.tsolicitud(id_solicitud)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE
/***********************************F-DEP-MAM-MAT-1-06/01/2017****************************************/

/***********************************I-DEP-MAM-MAT-0-07/01/2017****************************************/
----------------------------------
--COPY LINES TO dependencies.sql FILE
---------------------------------

select pxp.f_insert_testructura_gui ('MAT', 'SISTEMA');
select pxp.f_insert_testructura_gui ('REMA', 'MAT');
select pxp.f_delete_testructura_gui ('DET', 'MAT');
select pxp.f_insert_testructura_gui ('VBS', 'MAT');
select pxp.f_insert_testructura_gui ('CR', 'MAT');
select pxp.f_insert_testructura_gui ('ABS', 'MAT');
select pxp.f_insert_testructura_gui ('REMA.1', 'REMA');
select pxp.f_insert_testructura_gui ('REMA.2', 'REMA');
select pxp.f_insert_testructura_gui ('REMA.3', 'REMA');
select pxp.f_insert_testructura_gui ('REMA.4', 'REMA');
select pxp.f_insert_testructura_gui ('REMA.5', 'REMA');
select pxp.f_insert_testructura_gui ('REMA.3.1', 'REMA.3');
select pxp.f_insert_testructura_gui ('REMA.3.2', 'REMA.3');
select pxp.f_insert_testructura_gui ('REMA.3.3', 'REMA.3');
select pxp.f_insert_testructura_gui ('REMA.3.4', 'REMA.3');
select pxp.f_insert_testructura_gui ('REMA.3.5', 'REMA.3');
select pxp.f_insert_testructura_gui ('REMA.3.5.1', 'REMA.3.5');
select pxp.f_insert_testructura_gui ('REMA.3.5.1.1', 'REMA.3.5.1');
select pxp.f_insert_testructura_gui ('REMA.4.1', 'REMA.4');
select pxp.f_insert_testructura_gui ('VBS.1', 'VBS');
select pxp.f_insert_testructura_gui ('VBS.2', 'VBS');
select pxp.f_insert_testructura_gui ('VBS.3', 'VBS');
select pxp.f_insert_testructura_gui ('VBS.4', 'VBS');
select pxp.f_insert_testructura_gui ('VBS.5', 'VBS');
select pxp.f_insert_testructura_gui ('VBS.3.1', 'VBS.3');
select pxp.f_insert_testructura_gui ('VBS.3.2', 'VBS.3');
select pxp.f_insert_testructura_gui ('VBS.3.3', 'VBS.3');
select pxp.f_insert_testructura_gui ('VBS.3.4', 'VBS.3');
select pxp.f_insert_testructura_gui ('VBS.3.5', 'VBS.3');
select pxp.f_insert_testructura_gui ('VBS.3.5.1', 'VBS.3.5');
select pxp.f_insert_testructura_gui ('VBS.3.5.1.1', 'VBS.3.5.1');
select pxp.f_insert_testructura_gui ('VBS.4.1', 'VBS.4');
select pxp.f_insert_testructura_gui ('CR.1', 'CR');
select pxp.f_insert_testructura_gui ('CR.2', 'CR');
select pxp.f_insert_testructura_gui ('CR.3', 'CR');
select pxp.f_insert_testructura_gui ('CR.4', 'CR');
select pxp.f_insert_testructura_gui ('CR.5', 'CR');
select pxp.f_insert_testructura_gui ('CR.3.1', 'CR.3');
select pxp.f_insert_testructura_gui ('CR.3.2', 'CR.3');
select pxp.f_insert_testructura_gui ('CR.3.3', 'CR.3');
select pxp.f_insert_testructura_gui ('CR.3.4', 'CR.3');
select pxp.f_insert_testructura_gui ('CR.3.5', 'CR.3');
select pxp.f_insert_testructura_gui ('CR.3.5.1', 'CR.3.5');
select pxp.f_insert_testructura_gui ('CR.3.5.1.1', 'CR.3.5.1');
select pxp.f_insert_testructura_gui ('CR.4.1', 'CR.4');
select pxp.f_insert_testructura_gui ('ABS.1', 'ABS');
select pxp.f_insert_testructura_gui ('ABS.2', 'ABS');
select pxp.f_insert_testructura_gui ('ABS.3', 'ABS');
select pxp.f_insert_testructura_gui ('ABS.4', 'ABS');
select pxp.f_insert_testructura_gui ('ABS.5', 'ABS');
select pxp.f_insert_testructura_gui ('ABS.3.1', 'ABS.3');
select pxp.f_insert_testructura_gui ('ABS.3.2', 'ABS.3');
select pxp.f_insert_testructura_gui ('ABS.3.3', 'ABS.3');
select pxp.f_insert_testructura_gui ('ABS.3.4', 'ABS.3');
select pxp.f_insert_testructura_gui ('ABS.3.5', 'ABS.3');
select pxp.f_insert_testructura_gui ('ABS.3.5.1', 'ABS.3.5');
select pxp.f_insert_testructura_gui ('ABS.3.5.1.1', 'ABS.3.5.1');
select pxp.f_insert_testructura_gui ('ABS.4.1', 'ABS.4');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_MOD', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_ELI', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_SEL', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SIG_IME', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_ANT_INS', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_GETGES_GET', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'REMA.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'REMA.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_MOD', 'REMA.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_ELI', 'REMA.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'REMA.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'REMA.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'REMA.3.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'REMA.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'REMA.3.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'REMA.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_GETFILOP_IME', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PROVEEV_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('CONTA_ODT_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIG_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPARGES_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPAR_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPP_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPRE_SEL', 'REMA.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_REPPAGOS_SEL', 'REMA.3.5.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'REMA.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'REMA.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'REMA.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'REMA.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_MOD', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_ELI', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_SEL', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SIG_IME', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_ANT_INS', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'VBS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_MOD', 'VBS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_ELI', 'VBS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'VBS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_GETGES_GET', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'VBS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBS.3.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'VBS.3.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'VBS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_GETFILOP_IME', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PROVEEV_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('CONTA_ODT_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIG_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPARGES_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPAR_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPP_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPRE_SEL', 'VBS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_REPPAGOS_SEL', 'VBS.3.5.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'VBS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'VBS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'VBS.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_MOD', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_ELI', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_SEL', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SIG_IME', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_ANT_INS', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'CR.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_MOD', 'CR.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_ELI', 'CR.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'CR.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_GETGES_GET', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'CR.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'CR.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'CR.3.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'CR.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'CR.3.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'CR.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_GETFILOP_IME', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PROVEEV_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('CONTA_ODT_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIG_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPARGES_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPAR_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPP_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPRE_SEL', 'CR.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_REPPAGOS_SEL', 'CR.3.5.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'CR.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'CR.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'CR.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'CR.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_GATNREP_SEL', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_MOD', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_ELI', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_SEL', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SIG_IME', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_ANT_INS', 'ABS', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'ABS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_MOD', 'ABS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_ELI', 'ABS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'ABS.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_SOL_INS', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_INS', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_GETGES_GET', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_DET_SEL', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('RH_FUNCIOCAR_SEL', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('MAT_MATR_SEL', 'ABS.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'ABS.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'ABS.3.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'ABS.3.2', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DHW_SEL', 'ABS.3.3', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPPROC_SEL', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_INS', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_MOD', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_ELI', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DES_SEL', 'ABS.3.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_GETFILOP_IME', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_PROVEEV_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('CONTA_ODT_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIG_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPARGES_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPAR_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPP_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('PM_CONIGPRE_SEL', 'ABS.3.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('TES_REPPAGOS_SEL', 'ABS.3.5.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'ABS.3.5.1.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERSIGPRO_IME', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CHKSTA_IME', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPES_SEL', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DEPTIPES_SEL', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_FUNTIPES_SEL', 'ABS.4', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VERDOC_IME', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPDW_SEL', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIDOCPLAN_SEL', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_VISTA_SEL', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_INS', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_MOD', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_ELI', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DWF_SEL', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_CABMOM_IME', 'ABS.4.1', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_DOCWFAR_MOD', 'ABS.5', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPCOLFOR_SEL', 'REMA', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPCOLFOR_SEL', 'VBS', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPCOLFOR_SEL', 'CR', 'no');
select pxp.f_insert_tprocedimiento_gui ('WF_TIPCOLFOR_SEL', 'ABS', 'no');
select pxp.f_delete_tgui_rol ('REMA', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('MAT', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('SISTEMA', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.4.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.5.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.5.1.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.3.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('CR.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.4.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5.1.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('MAT', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('SISTEMA', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.4.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.5.1.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.4', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.3', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.3.1', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.2', 'GM - Solicitante');
select pxp.f_delete_tgui_rol ('REMA.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.5', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.4', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.4.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.5', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.5.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.5.1.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.4', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.3', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.2', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.3.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.2', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('CR.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.5', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.4', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.4.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.5', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.5.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.5.1.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.4', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.3', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.2', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.3.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.2', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('REMA.1', 'GM - Solicitante');
select pxp.f_insert_tgui_rol ('ABS', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('MAT', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('SISTEMA', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.5', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.4', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.4.1', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.5', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.5.1', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.5.1.1', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.4', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.3', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.2', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.3.1', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.2', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('ABS.1', 'GM - Auxiliar Abastecimientos');
select pxp.f_insert_tgui_rol ('VBS', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('MAT', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('SISTEMA', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.5', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.4', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.4.1', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.5', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.5.1', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.5.1.1', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.4', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.3', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.2', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.3.1', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.2', 'GM - Visto Bueno Solicitud');
select pxp.f_insert_tgui_rol ('VBS.1', 'GM - Visto Bueno Solicitud');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_GATNREP_SEL', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_MOD', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_ELI', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_ANT_INS', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SIG_IME', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_SEL', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'CR');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_FUNTIPES_SEL', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DEPTIPES_SEL', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERSIGPRO_IME', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CHKSTA_IME', 'CR.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_PROVEEV_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIG_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'CONTA_ODT_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPP_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPAR_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_GETFILOP_IME', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPRE_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPARGES_SEL', 'CR.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_REPPAGOS_SEL', 'CR.3.5.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPPROC_SEL', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_INS', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_MOD', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_ELI', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_SEL', 'CR.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DHW_SEL', 'CR.3.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.3.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_GETGES_GET', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'CR.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_MOD', 'CR.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_ELI', 'CR.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'CR.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_GATNREP_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_MOD', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_ELI', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_ANT_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SIG_IME', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_FUNTIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DEPTIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERSIGPRO_IME', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CHKSTA_IME', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_PROVEEV_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIG_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'CONTA_ODT_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPP_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPAR_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_GETFILOP_IME', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPRE_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPARGES_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_REPPAGOS_SEL', 'REMA.3.5.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPPROC_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_INS', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_MOD', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_ELI', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DHW_SEL', 'REMA.3.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.3.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_MOD', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_ELI', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_GETGES_GET', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_GATNREP_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_MOD', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_ELI', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_ANT_INS', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SIG_IME', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_FUNTIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DEPTIPES_SEL', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERSIGPRO_IME', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CHKSTA_IME', 'REMA.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.4.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_PROVEEV_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIG_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'CONTA_ODT_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPP_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPAR_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_GETFILOP_IME', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPRE_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPARGES_SEL', 'REMA.3.5');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'TES_REPPAGOS_SEL', 'REMA.3.5.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.5.1.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPPROC_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_INS', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_MOD', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_ELI', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_SEL', 'REMA.3.4');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DHW_SEL', 'REMA.3.3');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.3.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_MOD', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_ELI', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.2');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'PM_GETGES_GET', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA.1');
select pxp.f_delete_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_GATNREP_SEL', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_MOD', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_ELI', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_ANT_INS', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SIG_IME', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_SEL', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'CR');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_FUNTIPES_SEL', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DEPTIPES_SEL', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERSIGPRO_IME', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CHKSTA_IME', 'CR.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_PROVEEV_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIG_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'CONTA_ODT_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPP_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPAR_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'TES_GETFILOP_IME', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPRE_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPARGES_SEL', 'CR.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'TES_REPPAGOS_SEL', 'CR.3.5.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPPROC_SEL', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_INS', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_MOD', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_ELI', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_SEL', 'CR.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DHW_SEL', 'CR.3.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'CR.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'CR.3.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_GETGES_GET', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'CR.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'CR.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_MOD', 'CR.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_ELI', 'CR.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'CR.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_GATNREP_SEL', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_MOD', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_ELI', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_ANT_INS', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SIG_IME', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_SEL', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_FUNTIPES_SEL', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DEPTIPES_SEL', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERSIGPRO_IME', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CHKSTA_IME', 'REMA.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_PROVEEV_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIG_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'CONTA_ODT_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPP_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPAR_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'TES_GETFILOP_IME', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPRE_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_CONIGPARGES_SEL', 'REMA.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'TES_REPPAGOS_SEL', 'REMA.3.5.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPES_SEL', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPPROC_SEL', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_INS', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_MOD', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_ELI', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DES_SEL', 'REMA.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DHW_SEL', 'REMA.3.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIPDW_SEL', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_MOD', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_ELI', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_SEL', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_CABMOM_IME', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DWF_INS', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VERDOC_IME', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_TIDOCPLAN_SEL', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_VISTA_SEL', 'REMA.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'WF_DOCWFAR_MOD', 'REMA.3.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_MOD', 'REMA.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_ELI', 'REMA.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'RH_FUNCIOCAR_SEL', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'PM_GETGES_GET', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_INS', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_DET_SEL', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_SOL_INS', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Solicitante', 'MAT_MATR_SEL', 'REMA.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'RH_FUNCIOCAR_SEL', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_GATNREP_SEL', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_INS', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SOL_INS', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SOL_MOD', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SOL_ELI', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_ANT_INS', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SIG_IME', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SOL_SEL', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_MATR_SEL', 'ABS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DOCWFAR_MOD', 'ABS.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_FUNTIPES_SEL', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPES_SEL', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DOCWFAR_MOD', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DEPTIPES_SEL', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VERSIGPRO_IME', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_CHKSTA_IME', 'ABS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPDW_SEL', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_MOD', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_ELI', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_SEL', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_CABMOM_IME', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_INS', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VERDOC_IME', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIDOCPLAN_SEL', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VISTA_SEL', 'ABS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPDW_SEL', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_MOD', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_ELI', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_SEL', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_CABMOM_IME', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_INS', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VERDOC_IME', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIDOCPLAN_SEL', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VISTA_SEL', 'ABS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_PROVEEV_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_CONIG_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'CONTA_ODT_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_CONIGPP_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_CONIGPAR_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'TES_GETFILOP_IME', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_CONIGPRE_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_CONIGPARGES_SEL', 'ABS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'TES_REPPAGOS_SEL', 'ABS.3.5.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPDW_SEL', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_MOD', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_ELI', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_SEL', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_CABMOM_IME', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_INS', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VERDOC_IME', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIDOCPLAN_SEL', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VISTA_SEL', 'ABS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPES_SEL', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPPROC_SEL', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DES_INS', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DES_MOD', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DES_ELI', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DES_SEL', 'ABS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DHW_SEL', 'ABS.3.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIPDW_SEL', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_MOD', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_ELI', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_SEL', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_CABMOM_IME', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DWF_INS', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VERDOC_IME', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_TIDOCPLAN_SEL', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_VISTA_SEL', 'ABS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'WF_DOCWFAR_MOD', 'ABS.3.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'RH_FUNCIOCAR_SEL', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'PM_GETGES_GET', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_INS', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_SEL', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_SOL_INS', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_MATR_SEL', 'ABS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_INS', 'ABS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_MOD', 'ABS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_ELI', 'ABS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Auxiliar Abastecimientos', 'MAT_DET_SEL', 'ABS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'RH_FUNCIOCAR_SEL', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_GATNREP_SEL', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_INS', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SOL_INS', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SOL_MOD', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SOL_ELI', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_ANT_INS', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SIG_IME', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SOL_SEL', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_MATR_SEL', 'VBS');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DOCWFAR_MOD', 'VBS.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_FUNTIPES_SEL', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPES_SEL', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DOCWFAR_MOD', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DEPTIPES_SEL', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VERSIGPRO_IME', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_CHKSTA_IME', 'VBS.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPDW_SEL', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_MOD', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_ELI', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_SEL', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_CABMOM_IME', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_INS', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VERDOC_IME', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIDOCPLAN_SEL', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VISTA_SEL', 'VBS.4.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPDW_SEL', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_MOD', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_ELI', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_SEL', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_CABMOM_IME', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_INS', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VERDOC_IME', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIDOCPLAN_SEL', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VISTA_SEL', 'VBS.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_PROVEEV_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_CONIG_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'CONTA_ODT_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_CONIGPP_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_CONIGPAR_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'TES_GETFILOP_IME', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_CONIGPRE_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_CONIGPARGES_SEL', 'VBS.3.5');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'TES_REPPAGOS_SEL', 'VBS.3.5.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPDW_SEL', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_MOD', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_ELI', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_SEL', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_CABMOM_IME', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_INS', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VERDOC_IME', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIDOCPLAN_SEL', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VISTA_SEL', 'VBS.3.5.1.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPES_SEL', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPPROC_SEL', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DES_INS', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DES_MOD', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DES_ELI', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DES_SEL', 'VBS.3.4');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DHW_SEL', 'VBS.3.3');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIPDW_SEL', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_MOD', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_ELI', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_SEL', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_CABMOM_IME', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DWF_INS', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VERDOC_IME', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_TIDOCPLAN_SEL', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_VISTA_SEL', 'VBS.3.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'WF_DOCWFAR_MOD', 'VBS.3.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'RH_FUNCIOCAR_SEL', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'PM_GETGES_GET', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_INS', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_SEL', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_SOL_INS', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_MATR_SEL', 'VBS.2');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_INS', 'VBS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_MOD', 'VBS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_ELI', 'VBS.1');
select pxp.f_insert_trol_procedimiento_gui ('GM - Visto Bueno Solicitud', 'MAT_DET_SEL', 'VBS.1');

/***********************************F-DEP-MAM-MAT-0-07/01/2017****************************************/